config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "user/confirmations",
    passwords: "user/passwords",
    registrations: "user/registrations",
    sessions: "user/sessions",
    unlocks: "user/unlecks"
  }
  resources :friendships, only: %i[index destroy]
  resources :invitations, only: %i[index create destroy]
  resources :pending_invitations, only: %i[index update destroy]
  get "/status", to: "status#create"
  root "static#home"

  # Static pages
  get "/pricing", to: "static#pricing"
  get "/faq", to: "static#faq"
  get "/cookie-policy", to: "static#cookie_policy"
  get "/privacy-policy", to: "static#privacy_policy"

  # Sitemap. Remember to keep it up to date.
  get "/sitemap", to: "static#sitemap"

  # Internal
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  get "/fail", to: "fail#fail"
end

# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                         new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                        new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                            user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                          PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                          POST   /users/password(.:format)                                                                         devise/passwords#create
#                 cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
#                    new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
#                        user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
#                                          PUT    /users(.:format)                                                                                  devise/registrations#update
#                                          DELETE /users(.:format)                                                                                  devise/registrations#destroy
#                                          POST   /users(.:format)                                                                                  devise/registrations#create
#                    new_user_confirmation GET    /users/confirmation/new(.:format)                                                                 devise/confirmations#new
#                        user_confirmation GET    /users/confirmation(.:format)                                                                     devise/confirmations#show
#                                          POST   /users/confirmation(.:format)                                                                     devise/confirmations#create
#                          new_user_unlock GET    /users/unlock/new(.:format)                                                                       devise/unlocks#new
#                              user_unlock GET    /users/unlock(.:format)                                                                           devise/unlocks#show
#                                          POST   /users/unlock(.:format)                                                                           devise/unlocks#create
#                              friendships GET    /friendships(.:format)                                                                            friendships#index
#                               friendship DELETE /friendships/:id(.:format)                                                                        friendships#destroy
#                              invitations GET    /invitations(.:format)                                                                            invitations#index
#                                          POST   /invitations(.:format)                                                                            invitations#create
#                               invitation DELETE /invitations/:id(.:format)                                                                        invitations#destroy
#                      pending_invitations GET    /pending_invitations(.:format)                                                                    pending_invitations#index
#                       pending_invitation PATCH  /pending_invitations/:id(.:format)                                                                pending_invitations#update
#                                          PUT    /pending_invitations/:id(.:format)                                                                pending_invitations#update
#                                          DELETE /pending_invitations/:id(.:format)                                                                pending_invitations#destroy
#                                   status GET    /status(.:format)                                                                                 status#create
#                                     root GET    /                                                                                                 static#home
#                                  pricing GET    /pricing(.:format)                                                                                static#pricing
#                                      faq GET    /faq(.:format)                                                                                    static#faq
#                            cookie_policy GET    /cookie-policy(.:format)                                                                          static#cookie_policy
#                           privacy_policy GET    /privacy-policy(.:format)                                                                         static#privacy_policy
#                                  sitemap GET    /sitemap(.:format)                                                                                static#sitemap
#                        new_admin_session GET    /admins/sign_in(.:format)                                                                         devise/sessions#new
#                            admin_session POST   /admins/sign_in(.:format)                                                                         devise/sessions#create
#                    destroy_admin_session DELETE /admins/sign_out(.:format)                                                                        devise/sessions#destroy
#                       new_admin_password GET    /admins/password/new(.:format)                                                                    devise/passwords#new
#                      edit_admin_password GET    /admins/password/edit(.:format)                                                                   devise/passwords#edit
#                           admin_password PATCH  /admins/password(.:format)                                                                        devise/passwords#update
#                                          PUT    /admins/password(.:format)                                                                        devise/passwords#update
#                                          POST   /admins/password(.:format)                                                                        devise/passwords#create
#                   new_admin_confirmation GET    /admins/confirmation/new(.:format)                                                                devise/confirmations#new
#                       admin_confirmation GET    /admins/confirmation(.:format)                                                                    devise/confirmations#show
#                                          POST   /admins/confirmation(.:format)                                                                    devise/confirmations#create
#                         new_admin_unlock GET    /admins/unlock/new(.:format)                                                                      devise/unlocks#new
#                             admin_unlock GET    /admins/unlock(.:format)                                                                          devise/unlocks#show
#                                          POST   /admins/unlock(.:format)                                                                          devise/unlocks#create
#                              rails_admin        /admin                                                                                            RailsAdmin::Engine

app/controllers/pending_invitations_controller.rb
class PendingInvitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pending_invitation, only: %i[update destroy]

  def index
    @pending_invitations = current_user.pending_invitations.includes(requester: [:avatar_blob, :avatar_attachment])
  end

  # Updating a pending invitation is an implicit accept.
  def update
    @pending_invitation.accept!
    # TODO: send an email about the accepted invitation.
    redirect_back fallback_location: pending_invitations_url, notice: "You are now friends with #{@pending_invitation.requester.name}."
  end

  # Destroying a pending invitation is an implicit reject
  def destroy
    @pending_invitation.reject!
    redirect_back fallback_location: pending_invitations_url, notice: "The invitation from #{@pending_invitation.requester.name} was deleted."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pending_invitation
    @pending_invitation = current_user.pending_invitations.find(params[:id])
  end
end

app/views/pending_invitations/_pending_invitation.html.erb
<%= render "shared/card" do %>
  <%= render "shared/dropdown" do %>
    <%= mail_to pending_invitation.requester.email, class: drop_down_menu_item_class, role: "menuitem" do %>
      <%= fa(:envelope, "mr-4") %>
      Email
    <% end %>
    <%= button_to pending_invitation_url(pending_invitation), method: :put, class: drop_down_menu_item_class, role: "menuitem" do %>
      <%= fa(:check, "mr-4") %>
      Accept
    <% end %>
    <%= button_to pending_invitation_url(pending_invitation), method: :delete, data: {confirm: "Are you sure you want to delete the invitation from #{pending_invitation.requester.name}?"}, class: drop_down_menu_item_class, role: "menuitem" do %>
      <%= fa(:times, "mr-4") %>
      Delete
    <% end %>
  <% end %>
  <div class="flex flex-row overflow-hidden">
    <div class="mt-2 mr-10">
      <div class="inline-block relative">
        <div class="h-16 w-16 rounded-md bg-gray-100">
          <% if pending_invitation.requester.avatar.present? %>
            <%= image_tag pending_invitation.requester.avatar.variant(resize_to_fill: [80, 80]) %>
          <% else %>
            <%= image_tag gravatar_url(pending_invitation.requester.email_hash) %>
          <% end %>
        </div>
        <span class="absolute top-0 right-0 block h-4 w-4 transform -translate-y-1/2 translate-x-1/2 rounded-full text-white shadow-solid"/>
      </div>
    </div>
    <div>
      <h1 class="mb-4 text-2xl text-gray-800"><%= pending_invitation.requester.name %></h1>
      <div class="mb-4 text-gray-500 overflow-hidden whitespace-nowrap">
        <%= mail_to pending_invitation.requester.email, class: "hover:text-gray-400 focus:outline-none focus:underline transition ease-in-out duration-150" do %>
          <%= fa(:envelope, "mr-3") %>
          <%= pending_invitation.requester.email %>
        <% end %>
      </div>
      <div class="mb-4 text-gray-500 overflow-hidden whitespace-nowrap">
        <%= fa(:clock, "mr-3") %>
        Invited <%= time_ago_in_words(pending_invitation.invited_at) %> ago
      </div>
      
      <%= button_to pending_invitation_url(pending_invitation), method: :put, class: button_class do %>
        <%= fa(:check, "mr-4") %>
        Accept Invitation
      <% end %>
    </div>
  </div>
<% end %>

app/views/pending_invitations/index.html.erb
<% content_for :html_title, "Pending Invitations" %>

<% if @pending_invitations.empty? %>
  <%= render "shared/narrow_page", title: "Pending Invitations" do %>
    <p>There are no pending invitations. Invite some friends?</p>
    <%= render "invitations/form" %>
  <% end %>
<% else %>
  <div class="grid grid-cols-1 gap-3 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-2 xl:grid-cols-2
              m-0 mt-10 mb-10 lg:m-10">
    <% @pending_invitations.each do |pending_invitation| %>
      <%= render "pending_invitation", pending_invitation: pending_invitation %>
    <% end %>
    <%= render "shared/card" do %>
      <h1 class="mb-4 text-2xl text-gray-800">Invite some friends?</h1>
      <%= render "invitations/form" %>
    <% end %>
  </div>
<% end %>