config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "user/confirmations",
    passwords: "user/passwords",
    registrations: "user/registrations",
    sessions: "user/sessions",
    unlocks: "user/unlecks"
  }
  resources :friendships, only: %i[index destroy]
  resources :invitations, only: %i[index create destroy]
  resources :pending_invitations, only: %i[index update destroy]
  get "/status", to: "status#create"
  root "static#home"

  # Static pages
  get "/pricing", to: "static#pricing"
  get "/faq", to: "static#faq"
  get "/cookie-policy", to: "static#cookie_policy"
  get "/privacy-policy", to: "static#privacy_policy"

  # Sitemap. Remember to keep it up to date.
  get "/sitemap", to: "static#sitemap"

  # Internal
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  get "/fail", to: "fail#fail"
end

# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                         new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                        new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                            user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                          PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                          POST   /users/password(.:format)                                                                         devise/passwords#create
#                 cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
#                    new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
#                        user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
#                                          PUT    /users(.:format)                                                                                  devise/registrations#update
#                                          DELETE /users(.:format)                                                                                  devise/registrations#destroy
#                                          POST   /users(.:format)                                                                                  devise/registrations#create
#                    new_user_confirmation GET    /users/confirmation/new(.:format)                                                                 devise/confirmations#new
#                        user_confirmation GET    /users/confirmation(.:format)                                                                     devise/confirmations#show
#                                          POST   /users/confirmation(.:format)                                                                     devise/confirmations#create
#                          new_user_unlock GET    /users/unlock/new(.:format)                                                                       devise/unlocks#new
#                              user_unlock GET    /users/unlock(.:format)                                                                           devise/unlocks#show
#                                          POST   /users/unlock(.:format)                                                                           devise/unlocks#create
#                              friendships GET    /friendships(.:format)                                                                            friendships#index
#                               friendship DELETE /friendships/:id(.:format)                                                                        friendships#destroy
#                              invitations GET    /invitations(.:format)                                                                            invitations#index
#                                          POST   /invitations(.:format)                                                                            invitations#create
#                               invitation DELETE /invitations/:id(.:format)                                                                        invitations#destroy
#                      pending_invitations GET    /pending_invitations(.:format)                                                                    pending_invitations#index
#                       pending_invitation PATCH  /pending_invitations/:id(.:format)                                                                pending_invitations#update
#                                          PUT    /pending_invitations/:id(.:format)                                                                pending_invitations#update
#                                          DELETE /pending_invitations/:id(.:format)                                                                pending_invitations#destroy
#                                   status GET    /status(.:format)                                                                                 status#create
#                                     root GET    /                                                                                                 static#home
#                                  pricing GET    /pricing(.:format)                                                                                static#pricing
#                                      faq GET    /faq(.:format)                                                                                    static#faq
#                            cookie_policy GET    /cookie-policy(.:format)                                                                          static#cookie_policy
#                           privacy_policy GET    /privacy-policy(.:format)                                                                         static#privacy_policy
#                                  sitemap GET    /sitemap(.:format)                                                                                static#sitemap
#                        new_admin_session GET    /admins/sign_in(.:format)                                                                         devise/sessions#new
#                            admin_session POST   /admins/sign_in(.:format)                                                                         devise/sessions#create
#                    destroy_admin_session DELETE /admins/sign_out(.:format)                                                                        devise/sessions#destroy
#                       new_admin_password GET    /admins/password/new(.:format)                                                                    devise/passwords#new
#                      edit_admin_password GET    /admins/password/edit(.:format)                                                                   devise/passwords#edit
#                           admin_password PATCH  /admins/password(.:format)                                                                        devise/passwords#update
#                                          PUT    /admins/password(.:format)                                                                        devise/passwords#update
#                                          POST   /admins/password(.:format)                                                                        devise/passwords#create
#                   new_admin_confirmation GET    /admins/confirmation/new(.:format)                                                                devise/confirmations#new
#                       admin_confirmation GET    /admins/confirmation(.:format)                                                                    devise/confirmations#show
#                                          POST   /admins/confirmation(.:format)                                                                    devise/confirmations#create
#                         new_admin_unlock GET    /admins/unlock/new(.:format)                                                                      devise/unlocks#new
#                             admin_unlock GET    /admins/unlock(.:format)                                                                          devise/unlocks#show
#                                          POST   /admins/unlock(.:format)                                                                          devise/unlocks#create
#                              rails_admin        /admin                                                                                            RailsAdmin::Engine

app/views/layouts/_cookie_popup.html.erb
<div class="w-full bg-gray-100 flex items-center justify-center relative"
     data-controller="cookie-popup">
  <div class="w-full p-5 lg:px-24 bg-green-900">
    <div class="md:flex items-center">
      <div class="md:flex-1 px-3 mb-5 md:mb-0">
        <p class="text-center md:text-left text-white text-xs leading-tight md:pr-12">
          We and selected partners and related companies, use cookies and similar technologies as specified in our 
          <%= link_to "Cookie Policy", cookie_policy_url %>. You agree to consent to the use of
          these technologies by clicking Accept Cookies, or by continuing to browse this website.
        </p>
      </div>
      <div class="px-3 text-center">
        <button class="py-2 px-8 bg-green-600 hover:bg-green-700 text-white rounded font-bold text-sm shadow-xl"
                data-action="click->cookie-popup#acceptCookies">Accept Cookies</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-white">
  <div class="max-w-7xl mx-auto 
              pt-12 pb-2 px-4 
              overflow-hidden sm:px-6 lg:px-8">
    <%# Navigation %>
    <nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
      <div class="px-5 py-2">
        <%= footer_link "Frequently Asked Questions", faq_url %>
      </div>
      <div class="px-5 py-2">
        <%= footer_link "Enterprise", pricing_url %>
      </div>
      <div class="px-5 py-2">
        <%= footer_link "Cookie Policy", cookie_policy_url %>
      </div>
      <div class="px-5 py-2">
        <%= footer_link "Privacy Policy", privacy_policy_url %>
      </div>
      <div class="px-5 py-2">
        <%= mail_to "help@bestie.care", "Contact Us", class: footer_link_class %>
      </div>
    </nav>

    <%# Social links %>
    <div class="mt-8 flex justify-center space-x-6">
      <%= link_to "https://www.producthunt.com/upcoming/bestie", class: "text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Support us on our Product Hunt launch</span>
        <%= fab(:product_hunt, :lg) %> 
      <% end %>
      <%= link_to "https://twitter.com/bestie_care", class: "text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Follow us on Twitter</span>
        <%= fab(:twitter, :lg) %> 
      <% end %>
      <%= link_to "https://www.facebook.com/bestiecarecare", class: "text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Follow us on Facebook</span>
        <%= fab(:facebook, :lg) %> 
      <% end %>
      <%= link_to "https://www.instagram.com/bestie_care/", class: "text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Follow us on Instagram</span>
        <%= fab(:instagram, :lg) %> 
      <% end %>
      <%= link_to "https://www.linkedin.com/showcase/bestiecare/", class: "text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Follow us on LinkedIn</span>
        <%= fab(:linkedin, :lg) %> 
      <% end %>
    </div>

    <%# Copiright %>
    <p class="mt-8 text-center text-base text-gray-400">
      &copy; <%= Date.today.year %> <%= link_to "Flexpoint Tech Ltd", "https://flexpoint.tech", class: "text-base text-gray-500 underline hover:text-gray-900" %>. All rights reserved.
    </p>

    <%# Mandatory UK footer 
    https://www.gov.uk/running-a-limited-company/signs-stationery-and-promotional-material
    https://startsmarter.co.uk/do-your-website-and-email-footers-comply-with-uk-law/ %>
    <p class="mt-4 text-xs text-center text-gray-400">
      Flexpoint Tech Ltd is a company registered England and Wales (Company No. 10362469) Evolution House Iceni Court, Delft Way, Norwich, Norfolk, England, NR6 6BB, UK. -- <%= ENV["HEROKU_RELEASE_VERSION"] %>
    </p>
  </div>
</footer>

app/views/layouts/_top_bar.html.erb
<nav class="bg-green-800"
     data-controller="top-bar">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <%# Logo %>
        <div class="flex-shrink-0">
          <%= link_to utm(root_url, content: "top_bar_logo")  do %>
            <%= image_tag "white logomark.svg", class: "h-10 w-10", alt: "Bestie's logo" %>
          <% end %>
        </div>
        
        <%# Desktop menu, not visible on mobile %>
        <div class="hidden md:block">
          <%= render "layouts/top_bar_desktop_menu" %>
        </div>
      </div>

      <% if user_signed_in? %>
        <%# Bestie button %>
        <div class="flex-grow text-center">
          <%= link_to "I'm OK", status_url, class: button_class %>
        </div>

        <%# Pending invitations alert %>
        <% if current_user.pending_invitations.count > 0%>
          <%= link_to pending_invitations_url, class: "inline-flex items-center justify-center h-8 w-8 rounded-full bg-red-500 mr-4" do %>
            <div class="text-sm font-bold leading-none text-white"
                title="You have <%= current_user.pending_invitations.count %> pending invitations">
              <%= current_user.pending_invitations.count %>
            </div>
          <% end %>
        <% end %>

        <%# User menu %>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <%= render "layouts/top_bar_desktop_user_menu" %>
          </div>
        </div>
      <% end %>

      <%# Mobile menu button, visible only on mobile %>
      <div class="-mr-2 flex md:hidden">
        <button class="w-10 h-10 bg-green-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-800 focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
                data-action="click->top-bar#toggleMobileMenu"
                data-top-bar-target="mobileMenuButton">
          <span class="sr-only">Open menu</span>
          <div data-top-bar-target="mobileOpenMenuButton" aria-hidden="true">
            <%= fa(:bars, "fa-lg") %>
          </div>
          <div class="hidden" data-top-bar-target="mobileCloseMenuButton" aria-hidden="true">
            <%= fa(:times, "fa-lg") %>
          </div>
        </button>
      </div>
    </div>
  </div>

  <%# Mobile menu, visible only in mobile%>
  <div id="mobile-menu"
       class="hidden md:hidden"
       role="menu"
       data-top-bar-target="mobileMenu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <%= render "layouts/top_bar_mobile_menu" %>
    </div>
    <% if user_signed_in? %>
      <div class="pt-4 pb-3 border-t border-gray-700">
        <div class="flex items-center px-5">
          <div class="flex-shrink-0">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar.variant(resize_to_fill: [40, 40]), class: "h-10 w-10 rounded-full" %>
            <% else %>
              <%= image_tag gravatar_url(current_user.email_hash), class: "h-10 w-10 rounded-full" %>
            <% end %>
          </div>
          <div class="ml-3">
            <div class="text-base font-medium leading-none text-white"><%= current_user.name %></div>
            <div class="text-sm font-medium leading-none text-gray-400"><%= current_user.email %></div>
          </div>
        </div>
        <div class="mt-3 px-2 space-y-1">
          <%= top_bar_mobile_link "Profile", edit_user_registration_url %>
          <%= button_to "Sign out", destroy_user_session_url, method: :delete, class: top_bar_mobile_button_class, role: "menuitem" %>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_top_bar_desktop_menu.html.erb
<%# TODO: keep synchronized with the mobile menu in _top_bar_mobile_menu.html.erb %>
<div class="ml-10 flex items-baseline space-x-4">
  <% if !user_signed_in? %>
    <%= top_bar_desktop_link "Register", new_user_registration_url %>
    <%= top_bar_desktop_link "Log in", new_user_session_url %>
    <%= top_bar_desktop_link "Pricing", pricing_url %>
    <%= top_bar_desktop_link "FAQ", faq_url %>
  <% else %>
    <%= top_bar_desktop_link "Friends", friendships_url %>
    <%= top_bar_desktop_link "Invitations", invitations_url %>
    <%= top_bar_desktop_link "Pricing", pricing_url %>
    <%= top_bar_desktop_link "FAQ", faq_url %>
  <% end %>
  <%= top_bar_desktop_link "https://www.producthunt.com/upcoming/bestie" do %>
    Support us on Product Hunt <%= fa(:external_link_alt, "pl-1") %> 
  <% end %>
</div>

app/views/layouts/_top_bar_desktop_user_menu.html.erb
<div class="ml-3 relative">
  <div>
    <button class="flex max-w-xs 
                   bg-gray-800 rounded-full 
                   items-center 
                   text-sm 
                   focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
            aria-controls="user-menu"
            aria-expanded="false"
            data-action="click->top-bar#toggleDesktopUserMenu"
            data-top-bar-target="desktopUserMenuButton">
      <span class="sr-only">Open user menu</span>
      <% if current_user.avatar.present? %>
        <%= image_tag current_user.avatar.variant(resize_to_fill: [32, 32]), class: "h-8 w-8 rounded-full" %>
      <% else %>
        <%= image_tag gravatar_url(current_user.email_hash), class: "h-8 w-8 rounded-full" %>
      <% end %>
    </button>
  </div>
  <div id="user-menu"
       class="hidden origin-top-right absolute right-0 z-50
              w-48 
              mt-2
              bg-gray-200 shadow-lg rounded-md ring-1 ring-black ring-opacity-5
              overflow-hidden"
       role="menu"
       aria-orientation="vertical"
       aria-labelledby="user-menu"
       data-top-bar-target="desktopUserMenu">
    <%= link_to "Profile", edit_user_registration_url, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-300", role: "menuitem" %>
    <%= button_to "Sign out", destroy_user_session_url, method: :delete, class: "block px-4 py-2 w-full bg-gray-200 text-sm text-left text-gray-700 hover:bg-gray-300 cursor-pointer", role: "menuitem" %>
  </div>
</div>

app/views/layouts/_top_bar_mobile_menu.html.erb
<%# TODO: keep synchronized with the mobile menu in _top_bar_desktop_menu.html.erb %>
<% if !user_signed_in? %>
  <%= top_bar_mobile_link "Register", new_user_registration_url %>
  <%= top_bar_mobile_link "Log in", new_user_session_url %>
  <%= top_bar_mobile_link "Pricing", pricing_url %>
  <%= top_bar_mobile_link "FAQ", faq_url %>
<% else %>
  <%= top_bar_mobile_link "Friends", friendships_url %>
  <%= top_bar_mobile_link "Invitations", invitations_url %>
  <%= top_bar_mobile_link "Pricing", pricing_url %>
  <%= top_bar_mobile_link "FAQ", faq_url %>
<% end %>
<%= top_bar_mobile_link "https://www.producthunt.com/upcoming/bestie" do %>
  Support us on Product Hunt <%= fa(:external_link_alt, "pl-1") %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%# Define data layer for Google tag manager https://developers.google.com/tag-manager/devguide %>
    <script>
      dataLayer = [];
    </script>
    <% if user_signed_in? %>
      <script>
        dataLayer.push({"user_id": "<%= current_user.id %>"});
      </script>
    <% end %>

    <%# Google Tag Manager: https://developers.google.com/tag-manager/quickstart %>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<%= ENV["GOOGLE_TAG_MANAGER_ID"] %>');</script>

    <% title = "#{content_for?(:html_title) ? "#{yield :html_title} - " : ""}Bestie - Don't ask for help, get help." %>
    <title><%= title %></title>
    <meta name="apple-mobile-web-app-title" content="Bestie" />
    <meta name="application-name" content="Bestie" />
    <meta name="og:site_name" content="Bestie" />
    <meta name="og:title" content="<%= title%>"/>
    <meta name="og:image" content="<%= image_url "logomark - 1024x1024.png" %>"/>
    <meta name="og:description" conten="Asking for help is the hardest when you need it the most. Don't ask for help, get help." />
    <meta name="description" content="Asking for help is the hardest when you need it the most. Don't ask for help, get help." />

    <%# https://realfavicongenerator.net/favicon_result?file_id=p1f3gakv5b1c2kf8h1v521re91sn6 %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#065f46">
    <meta name="apple-mobile-web-app-title" content="Bestie">
    <meta name="application-name" content="Bestie">
    <meta name="msapplication-TileColor" content="#065f46">
    <meta name="theme-color" content="#065F46">
   
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <link href="https://rsms.me/inter/inter.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body class="flex flex-col min-h-screen antialiased font-sans bg-gray-300">
    <%# Google Tag Manager (noscript): https://developers.google.com/tag-manager/quickstart %>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= ENV["GOOGLE_TAG_MANAGER_ID"] %>"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

    <%= render "layouts/top_bar" %>

    <main class="flex-grow max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </main>

    <%= render "layouts/cookie_popup" %>
    <%= render "layouts/footer" %>
  </body>
</html>